export const TEXTS = {
  PT: {
    MAIN_TITLE: 'PREPARE-SE PARA A BATALHA',
    MAIN_SUBTITLE: 'DERROTE A IA OU DESAFIE UM AMIGO',
    PLAYER_NAME_LABEL: 'NOME DO PILOTO',
    PLAYER_NAME_PLACEHOLDER: 'Seu nome',
    STATUS_NAME_REQUIRED: 'Defina um nome antes de entrar.',
    BTN_TRAINING: 'TREINO SOLO (VS IA)',
    HOST_TITLE: 'CRIAR SALA',
    HOST_BTN: 'CRIAR',
    GUEST_TITLE: 'ENTRAR EM SALA',
    GUEST_BTN: 'ENTRAR',
    INPUT_PLACEHOLDER: 'CODIGO',
    STATUS_CREATING: 'Criando sala...',
    STATUS_CREATED: 'SALA CRIADA: {0} (Aguardando P2...)',
    STATUS_P2_CONNECTED: 'JOGADOR 2 CONECTADO!',
    STATUS_JOINING: 'Entrando...',
    STATUS_NOT_FOUND: 'Sala nao encontrada!',
    STATUS_ERROR: 'Erro: ',
    ROOM_LABEL: 'SALA:',
    SELECT_INSTRUCT: 'ESCOLHA 3 NAVES',
    BTN_READY: 'CONFIRMAR FROTA',
    STATUS_WAITING: 'AGUARDANDO OPONENTE...',
    TURN_YOURS: 'SUA VEZ',
    TURN_OPP: 'VEZ DO OPONENTE',
    SELECT_SHIP: 'SELECIONE UMA NAVE',
    BTN_EXECUTE: 'EXECUTAR',
    BTN_MOVE: 'X MOVER',
    BTN_ATK: 'X ATACAR',
    TIMER_LABEL: 'TEMPO: ',
    WAITING_LABEL: 'AGUARDANDO...',
    EXECUTING_LABEL: 'PROCESSANDO...',
    BLOCKED_LABEL: 'BLOQUEADO',
    CRASH_LABEL: 'COLISAO!',
    BTN_SURRENDER: 'RENDER-SE',
    SURRENDER_CONFIRM: 'Tem certeza? Isso contara como DERROTA.',
    VICTORY: 'VITORIA',
    DEFEAT: 'DERROTA',
    DRAW: 'EMPATE',
    BTN_RESTART: 'REINICIAR',
    REMATCH_SENT: 'Pedido de nova partida enviado. Aguardando adversario...',
    REMATCH_OPP: 'O adversario quer nova partida. Clique em REINICIAR para aceitar.',
    REMATCH_STARTING: 'Ambos aceitaram. Iniciando nova partida...',
    BTN_MENU: 'MENU PRINCIPAL',
    DESC_FLUX: 'Alta velocidade, baixa vida.',
    DESC_VECTOR: 'Status balanceados.',
    DESC_COLOSSUS: 'Tanque pesado, muito lento.',
    CHAT_TITLE: 'CHAT DA PARTIDA',
    CHAT_PLACEHOLDER: 'Digite e pressione Enter...',
    CHAT_SEND: 'ENVIAR'
  },
  EN: {
    MAIN_TITLE: 'PREPARE FOR BATTLE',
    MAIN_SUBTITLE: 'DEFEAT THE AI OR CHALLENGE A FRIEND',
    PLAYER_NAME_LABEL: 'PILOT NAME',
    PLAYER_NAME_PLACEHOLDER: 'Your name',
    STATUS_NAME_REQUIRED: 'Set a name before joining.',
    BTN_TRAINING: 'SOLO TRAINING (VS AI)',
    HOST_TITLE: 'HOST GAME',
    HOST_BTN: 'CREATE',
    GUEST_TITLE: 'JOIN GAME',
    GUEST_BTN: 'JOIN',
    INPUT_PLACEHOLDER: 'CODE',
    STATUS_CREATING: 'Creating room...',
    STATUS_CREATED: 'ROOM CREATED: {0} (Waiting P2...)',
    STATUS_P2_CONNECTED: 'PLAYER 2 CONNECTED!',
    STATUS_JOINING: 'Joining...',
    STATUS_NOT_FOUND: 'Room not found!',
    STATUS_ERROR: 'Error: ',
    ROOM_LABEL: 'ROOM:',
    SELECT_INSTRUCT: 'SELECT 3 SHIPS',
    BTN_READY: 'CONFIRM FLEET',
    STATUS_WAITING: 'WAITING FOR OPPONENT...',
    TURN_YOURS: 'YOUR TURN',
    TURN_OPP: "OPPONENT'S TURN",
    SELECT_SHIP: 'SELECT A SHIP',
    BTN_EXECUTE: 'EXECUTE',
    BTN_MOVE: 'X MOVE',
    BTN_ATK: 'X ATTACK',
    TIMER_LABEL: 'TIME: ',
    WAITING_LABEL: 'WAITING...',
    EXECUTING_LABEL: 'EXECUTING...',
    BLOCKED_LABEL: 'BLOCKED',
    CRASH_LABEL: 'CRASH!',
    BTN_SURRENDER: 'SURRENDER',
    SURRENDER_CONFIRM: 'Are you sure? This counts as DEFEAT.',
    VICTORY: 'VICTORY',
    DEFEAT: 'DEFEAT',
    DRAW: 'DRAW',
    BTN_RESTART: 'RESTART',
    REMATCH_SENT: 'Rematch request sent. Waiting for opponent...',
    REMATCH_OPP: 'Opponent wants a rematch. Click RESTART to accept.',
    REMATCH_STARTING: 'Both accepted. Starting a new match...',
    BTN_MENU: 'MAIN MENU',
    DESC_FLUX: 'High speed, low HP.',
    DESC_VECTOR: 'Balanced stats.',
    DESC_COLOSSUS: 'Heavy tank, very slow.',
    CHAT_TITLE: 'MATCH CHAT',
    CHAT_PLACEHOLDER: 'Type and press Enter...',
    CHAT_SEND: 'SEND'
  }
};
